CREATE DATABASE IF NOT EXISTS POLARIS_DW;
SET GLOBAL default_table_type = 'columnstore';
USE POLARIS_DW;
CREATE TABLE IF NOT EXISTS CUSTOMER_DIMENSION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORGANIZATION_ID VARCHAR(36) NOT NULL,
    CUSTOMER_NAME VARCHAR(128) NOT NULL,
    TENANT_SHORT_ID VARCHAR(4) NOT NULL,
    STATE VARCHAR(30) NOT NULL,
    IS_DELETED TINYINT DEFAULT 0 ,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CREATE_DATETIME DATETIME(6) NOT NULL,
    UPDATE_DATETIME DATETIME(6) NOT NULL,
    SORT KEY (IS_DELETED,ORGANIZATION_ID, CUSTOMER_NAME, STATE),
    SHARD KEY(ID)
); 

CREATE TABLE IF NOT EXISTS APPLICATION_WITH_BRANCHES_DIMENSION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORGANIZATION_ID VARCHAR(36) NOT NULL,
    APPLICATION_ID VARCHAR(36) NOT NULL,
    APPLICATION_NAME VARCHAR(256) NOT NULL,
    APPLICATION_DESCRIPTION VARCHAR(2048),
    IS_APPLICATION_DELETED TINYINT DEFAULT 0 ,
    APPLICATION_CREATED_AT DATETIME(6) NOT NULL,
    APPLICATION_UPDATED_AT DATETIME(6) NOT NULL,
    PROJECT_ID VARCHAR(36) NOT NULL,
    PROJECT_NAME VARCHAR(256) NOT NULL,
    PROJECT_DESCRIPTION VARCHAR(2048),
    IS_PROJECT_DELETED TINYINT DEFAULT 0 ,
    PROJECT_CREATED_AT DATETIME(6) NOT NULL,
    PROJECT_UPDATED_AT DATETIME(6) NOT NULL,
    PROJECT_STATE VARCHAR(255) NOT NULL,
    PROJECT_ENTRY_POINT_URL VARCHAR(255),
    BRANCH_ID VARCHAR(36) NOT NULL,
    BRANCH_NAME VARCHAR(256) NOT NULL,
    BRANCH_DESCRIPTION VARCHAR(256),
    BRANCH_IS_DEFAULT TINYINT DEFAULT 0 ,
    IS_BRANCH_DELETED TINYINT DEFAULT 0 ,
    BRANCH_CREATED_AT DATETIME(6) NOT NULL,
    BRANCH_UPDATED_AT DATETIME(6) NOT NULL,
    CREATE_DATETIME DATETIME(6) NOT NULL,
    UPDATE_DATETIME DATETIME(6) NOT NULL,
    SORT KEY (IS_APPLICATION_DELETED,ORGANIZATION_ID, APPLICATION_ID,PROJECT_STATE,PROJECT_ID),
    SHARD KEY(ID)
); 




CREATE TABLE `CUSTOMER_DIMENSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORGANIZATION_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `CUSTOMER_NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `TENANT_SHORT_ID` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `STATE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `IS_DELETED` tinyint(4) DEFAULT 0,
  `CREATED_AT` datetime(6) NOT NULL,
  `UPDATED_AT` datetime(6) NOT NULL,
  `CREATE_DATETIME` datetime(6) NOT NULL,
  `UPDATE_DATETIME` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`),
  SORT KEY `IS_DELETED` (`IS_DELETED`,`ORGANIZATION_ID`,`CUSTOMER_NAME`,`STATE`),
  SHARD KEY `__SHARDKEY` (`ID`)
) AUTO_INCREMENT=3000000 AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES,NO_AUTO_CREATE_USER'





CREATE TABLE IF NOT EXISTS APPLICATION_DIMENSION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORGANIZATION_ID VARCHAR(36) NOT NULL,
    APPLICATION_ID VARCHAR(36) NOT NULL,
    APPLICATION_NAME VARCHAR(256) NOT NULL,
    APPLICATION_DESCRIPTION VARCHAR(2048),
    IS_APPLICATION_DELETED TINYINT DEFAULT 0 ,
    APPLICATION_CREATED_AT DATETIME(6) NOT NULL,
    APPLICATION_UPDATED_AT DATETIME(6) NOT NULL,
    PROJECT_ID VARCHAR(36) NOT NULL,
    PROJECT_NAME VARCHAR(256) NOT NULL,
    PROJECT_DESCRIPTION VARCHAR(2048),
    IS_PROJECT_DELETED TINYINT DEFAULT 0 ,
    PROJECT_CREATED_AT DATETIME(6) NOT NULL,
    PROJECT_UPDATED_AT DATETIME(6) NOT NULL,
    PROJECT_STATE VARCHAR(255) NOT NULL,
    PROJECT_ENTRY_POINT_URL VARCHAR(255),
    CREATE_DATETIME DATETIME(6) NOT NULL,
    UPDATE_DATETIME DATETIME(6) NOT NULL,
    SORT KEY (IS_APPLICATION_DELETED,ORGANIZATION_ID, APPLICATION_ID,PROJECT_STATE,PROJECT_ID, BRANCH_ID),
    SHARD KEY(ID)
); 



CREATE TABLE `APPLICATION_DIMENSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORGANIZATION_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `APPLICATION_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `APPLICATION_NAME` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `APPLICATION_DESCRIPTION` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `IS_APPLICATION_DELETED` tinyint(4) DEFAULT 0,
  `APPLICATION_CREATED_AT` datetime(6) NOT NULL,
  `APPLICATION_UPDATED_AT` datetime(6) NOT NULL,
  `PROJECT_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `PROJECT_NAME` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `PROJECT_DESCRIPTION` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `IS_PROJECT_DELETED` tinyint(4) DEFAULT 0,
  `PROJECT_CREATED_AT` datetime(6) NOT NULL,
  `PROJECT_UPDATED_AT` datetime(6) NOT NULL,
  `PROJECT_STATE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `PROJECT_ENTRY_POINT_URL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CREATE_DATETIME` datetime(6) NOT NULL,
  `UPDATE_DATETIME` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`),
  SORT KEY `IS_APPLICATION_DELETED` (`IS_APPLICATION_DELETED`,`ORGANIZATION_ID`,`APPLICATION_ID`,`PROJECT_STATE`,`PROJECT_ID`),
  SHARD KEY `__SHARDKEY` (`ID`)
) AUTO_INCREMENT=6000000 AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES,NO_AUTO_CREATE_USER'





CREATE TABLE IF NOT EXISTS SCAN_FACT ( 
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_DIM_ID BIGINT NOT NULL,
    APPLICATION_DIM_ID BIGINT NOT NULL,
    ORGANIZATION_ID VARCHAR(36) NOT NULL,
    APPLICATION_ID VARCHAR(36) NOT NULL,
    PROJECT_ID VARCHAR(36) NOT NULL,
    TEST_ID  VARCHAR(36) NOT NULL,
    BRANCH_ID VARCHAR(36),
    ENTITLEMENT_ID VARCHAR(36) NOT NULL,
    SUBSCRIPTION_ID VARCHAR(36) NOT NULL,
    CATALOG_ID VARCHAR(36) NOT NULL,
    TEST_SHORT_ID VARCHAR(7) NOT NULL,
    STREAM_ID VARCHAR(36) NOT NULL,
    SCAN_ID VARCHAR(36) ,
    SCAN_MODE VARCHAR(100) NOT NULL,
    TEST_MODE VARCHAR(100) NOT NULL,
    TOOL_NAME VARCHAR(255) NOT NULL, 
    ASSESSMENT_TYPE VARCHAR(100) NOT NULL,
    WORKFLOW_TYPE VARCHAR(36) NOT NULL,
    SCAN_STATE VARCHAR(255) NOT NULL,
    TRIAGE VARCHAR(25) NOT NULL,
    IS_DELETED TINYINT DEFAULT 0 ,
    IS_DEFAULT_BRANCH TINYINT DEFAULT 0 ,
    START_DATE DATETIME(6) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CREATE_DATETIME DATETIME(6) NOT NULL,
    UPDATE_DATETIME DATETIME(6) NOT NULL,
    SORT KEY (IS_DELETED,ASSESSMENT_TYPE,ORGANIZATION_ID, APPLICATION_ID,SCAN_STATE,PROJECT_ID),
    SHARD KEY(ID)
); 



CREATE TABLE `SCAN_FACT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_DIM_ID` bigint(20) NOT NULL,
  `APPLICATION_DIM_ID` bigint(20) NOT NULL,
  `ORGANIZATION_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `APPLICATION_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `PROJECT_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `TEST_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `BRANCH_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ENTITLEMENT_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `SUBSCRIPTION_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `CATALOG_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `TEST_SHORT_ID` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `STREAM_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `SCAN_ID` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SCAN_MODE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `TEST_MODE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `TOOL_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `ASSESSMENT_TYPE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `WORKFLOW_TYPE` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `SCAN_STATE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `TRIAGE` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `IS_DELETED` tinyint(4) DEFAULT 0,
  `IS_DEFAULT_BRANCH` tinyint(4) DEFAULT 0,
  `START_DATE` datetime(6) NOT NULL,
  `CREATED_AT` datetime(6) NOT NULL,
  `UPDATED_AT` datetime(6) NOT NULL,
  `CREATE_DATETIME` datetime(6) NOT NULL,
  `UPDATE_DATETIME` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`),
  SORT KEY `IS_DELETED` (`IS_DELETED`,`ASSESSMENT_TYPE`,`ORGANIZATION_ID`,`APPLICATION_ID`,`SCAN_STATE`,`PROJECT_ID`),
  SHARD KEY `__SHARDKEY` (`ID`)
) AUTO_INCREMENT=2000000 AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES,NO_AUTO_CREATE_USER'