CREATE DATABASE IF NOT EXISTS POLARIS_DW;
SET GLOBAL default_table_type = 'columnstore';
USE POLARIS_DW;
CREATE TABLE IF NOT EXISTS CUSTOMER_DIMENSION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORGANIZATION_ID VARCHAR(36) NOT NULL,
    CUSTOMER_NAME VARCHAR(128) NOT NULL,
    TENANT_SHORT_ID VARCHAR(4) NOT NULL,
    STATE VARCHAR(30) NOT NULL,
    IS_DELETED TINYINT DEFAULT 0 ,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CREATE_DATETIME DATETIME(6) NOT NULL,
    UPDATE_DATETIME DATETIME(6) NOT NULL,
    SORT KEY (IS_DELETED,ORGANIZATION_ID, CUSTOMER_NAME, STATE),
    SHARD KEY(ID)
); 

CREATE TABLE IF NOT EXISTS APPLICATION_DIMENSION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORGANIZATION_ID VARCHAR(36) NOT NULL,
    APPLICATION_ID VARCHAR(36) NOT NULL,,
    APPLICATION_NAME VARCHAR(128) NOT NULL,
    TENANT_SHORT_ID VARCHAR(4) NOT NULL,
    STATE VARCHAR(30) NOT NULL,
    IS_DELETED TINYINT DEFAULT 0 ,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CREATE_DATETIME DATETIME(6) NOT NULL,
    UPDATE_DATETIME DATETIME(6) NOT NULL,
    SORT KEY (IS_DELETED,ORGANIZATION_ID, APPLICATION_ID,STATE),
    SHARD KEY(ID)
); 