CREATE DATABASE IF NOT EXISTS POLARIS_DW;
SET GLOBAL default_table_type = 'columnstore';
USE POLARIS_DW;
CREATE TABLE IF NOT EXISTS CUSTOMER_DIMENSION (
    ID BIGINT PRIMARY KEY,
    ORGANIZATION_ID VARCHAR(36),
    CUSTOMER_NAME VARCHAR(128),
    TENANT_SHORT_ID VARCHAR(4),
    STATE VARCHAR(30),
    IS_DELETED TINYINT DEFAULT 0 ,
    CREATED_AT DATETIME(6),
    CREATE_DATETIME DATETIME(6),
    UPDATE_DATETIME DATETIME(6),
    SORT KEY (IS_DELETED,ORGANIZATION_ID, CUSTOMER_NAME, STATE),
    SHARD KEY(ID)
); 