SELECT * FROM POLARIS_DW.CUSTOMER_DIMENSION;

select count(*) from POLARIS_DW.CUSTOMER_DIMENSION;



SELECT 
  S.ID, C.ID as custdim,C.ORGANIZATION_ID, C.CUSTOMER_NAME,A.ID as appdim, A.ORGANIZATION_ID as AORGID, A.APPLICATION_ID,A.APPLICATION_NAME, A.PROJECT_ID, A.PROJECT_NAME
,S.ORGANIZATION_ID as SORGID, S.APPLICATION_ID as SAPPID, S.PROJECT_ID as SPROJID, S.ASSESSMENT_TYPE, S.SCAN_MODE, S.TEST_MODE,S.TOOL_NAME
,  S.TEST_ID, S.TEST_SHORT_ID, S.SCAN_STATE
FROM SCAN_FACT as S
JOIN CUSTOMER_DIMENSION as C on S.CUSTOMER_DIM_ID = C.ID
JOIN APPLICATION_DIMENSION as A on S.APPLICATION_DIM_ID = A.ID



SELECT 
  S.ID, C.ID as custdim,C.ORGANIZATION_ID, C.CUSTOMER_NAME,A.ID as appdim, A.ORGANIZATION_ID as AORGID, A.APPLICATION_ID,A.APPLICATION_NAME, A.PROJECT_ID, A.PROJECT_NAME
,S.ORGANIZATION_ID as SORGID, S.APPLICATION_ID as SAPPID, S.PROJECT_ID as SPROJID, S.ASSESSMENT_TYPE, S.SCAN_MODE, S.TEST_MODE,S.TOOL_NAME
,  S.TEST_ID, S.TEST_SHORT_ID, S.SCAN_STATE
FROM SCAN_FACT as S
JOIN CUSTOMER_DIMENSION as C on S.CUSTOMER_DIM_ID = C.ID
JOIN APPLICATION_DIMENSION as A on S.APPLICATION_DIM_ID = A.ID


SELECT 
  S.ID, C.ID as custdim,C.ORGANIZATION_ID, C.CUSTOMER_NAME,A.ID as appdim, A.ORGANIZATION_ID as AORGID, A.APPLICATION_ID,A.APPLICATION_NAME, A.PROJECT_ID, A.PROJECT_NAME
,S.ORGANIZATION_ID as SORGID, S.APPLICATION_ID as SAPPID, S.PROJECT_ID as SPROJID, S.ASSESSMENT_TYPE, S.SCAN_MODE, S.TEST_MODE,S.TOOL_NAME
,  S.TEST_ID, S.TEST_SHORT_ID, S.SCAN_STATE, S.START_DATE
FROM SCAN_FACT as S
JOIN CUSTOMER_DIMENSION as C on S.CUSTOMER_DIM_ID = C.ID
JOIN APPLICATION_DIMENSION as A on S.APPLICATION_DIM_ID = A.ID
